config/routes.rb
Rails.application.routes.draw do
  namespace :user_controllers, path: "/" do 
    root to: 'home_pages#index'
    get  '/show',    to: 'home_pages#show'
    namespace :authentications do 
      resource :registrations, only: [:new, :create]
      resource :sessions, only: [:new, :create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_one :visitor, as: :referer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :visitor, as: :referer
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  extend AuthenticationLib::VisitorClassAuthenticationLib
  include AuthenticationLib::VisitorInstanceAuthenticationLib

  attr_accessor :remember_token, :reset_token

  enum provider: [:facebook, :google, :instagram]
  
  has_secure_password

  belongs_to :refer, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  layout :choose_layout

  private
  def choose_layout 
    if true
      "users_layout"
    else
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/user_controllers/authentications/registrations_controller.rb
class UserControllers::Authentications::RegistrationsController < ApplicationController
  def new
    @registration_form = UserForms::RegistrationForm.new visitor: Visitor.new
    respond_to do |format|
      format.js
    end
  end

  def create 
    @registration_form = UserForms::RegistrationForm.new visitor: Visitor.new 
    respond_to do |format|
      if @registration_form.validate registration_form_params 
        @registration_form.save
        format.js 
      else 
        format.js do 
          render partial: 'shared/errors/errors', 
            locals: { error_messages: @registration_form.errors.messages }
        end 
      end
    end
  end

  private
  def registration_form_params
    params.require(:visitor).permit :name, :email, 
      :password, :password_confirmation
  end
end

app/controllers/user_controllers/authentications/sessions_controller.rb
class UserControllers::Authentications::SessionsController < ApplicationController
  def new    
    respond_to do |format| 
      format.js
    end
  end

  def create 
    visitor = Visitor.find_by email: params[:session][:email]
    respond_to do |format| 
      if visitor && visitor.authenticate(params[:session][:password])
          log_in visitor
          params[:session][:remember_me] == '1' ? remember(visitor) : forget(visitor)
          format.js 
      else
        format.js do 
          render partial: "shared/errors/errors", 
            locals: { error_messages: { 
              invalid_email_and_password: ["Combination"] } 
            }
        end
      end
    end
  end 
end

app/controllers/user_controllers/home_pages_controller.rb
class UserControllers::HomePagesController < ApplicationController
  def index
  end

  def show
    @product= User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title=""
    base_title = "Cinema House"
    if page_title.empty?
      base_title 
    else
      page_title + " | " + base_title
    end
  end

  def error_element_id error_key 
    controller.controller_name + "-" + 
      error_key.to_s.split('_').join('-') + "-error"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_visitor 
    if visitor_id = session[:visitor_id]
      @current_visitor = Visitor.find_by id: visitor_id 
    elsif visitor_id = cookies.signed[:visitor_id]
      visitor = Visitor.find_by id: visitor_id 
      if visitor && visitor.authenticate?(:remember, cookies[:remember_token])
        login visitor 
        @current_visitor = visitor
      end
    end
  end

  def current_refer 
    @current_refer = current_visitor.refer 
  end

  def log_in visitor
    session[:visitor_id] = visitor.id   
  end
  
  def log_out visitor 
    forget curent_visitor 
    session.delete[:visitor_id]
    @current_visitor = nil 
    @current_refer = nil
  end 

  def logged_in?
    current_visitor.present?  
  end

  def remember visitor 
    visitor.remember 
    cookies.permanent.signed[:visitor_id] = visitor.id 
    cookies.permanent[:remember_token] = visitor.remember_token
  end 

  def forget visitor 
    visitor.forget 
    cookies.delete :visitor_id 
    cookies.delete :remember_token
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CinemaHouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="wrapper">
      <%= render 'layouts/side_nav' %>
      <div id="content">
        <%= yield %>
      </div>
    </div>
    <%= render 'modals/login_modal' %>
  </body>
</html>

app/views/layouts/users/_header.html.erb
<section id="page-header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="site-name-logo-container">
                <button type="button" id="sidebarCollapse" class="btn btn-info">
                  <i class="fas fa-align-left"></i>
              </button>
                <div class="site-name-header">
                    <%= image_tag "site-name.png", class: "site-name" %>
                </div>
            </div>

            <form id="search-form" class="navbar-form" role="search">
                <div class="input-group add-on">
                    <input class="form-control" placeholder="Search" name="srch-term" id="srch-term"
                        type="text">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                          <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <% if logged_in? %>
              <button class="btn btn-dark d-inline-block d-lg-none" id="login-action-toggler"
                  type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <i class="fas fa-align-justify"></i>
              </button>
            <% else %>
              <%= button_tag id: "login-button", class: "btn btn-info d-inline-block" do %>
                <%= content_tag :span, "Đăng nhập" %>
              <% end %>
            <% end %>
        </div>
    </nav>
</section>

app/views/layouts/users/_side_nav.html.erb
<nav id="sidebar">
      <ul class="list-unstyled components" id="sidebar-body">
          <li class="active">
              <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                  <i class="fas fa-home"></i>
                  Quần
              </a>
              <ul class="collapse list-unstyled" id="homeSubmenu">
                  <li>
                      <a href="#">Quần đùi</a>
                  </li>
                  <li>
                      <a href="#">Quần què</a>
                  </li>
                  <li>
                      <a href="#">Quần què</a>
                  </li>
              </ul>
          </li>
          <li>
              <a href="#">
                  <i class="fas fa-briefcase"></i>
                  About
              </a>
              <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                  <i class="fas fa-copy"></i>
                  Áo
              </a>
              <ul class="collapse list-unstyled" id="pageSubmenu">
                  <li>
                      <a href="#">Page 1</a>
                  </li>
                  <li>
                      <a href="#">Page 2</a>
                  </li>
                  <li>
                      <a href="#">Page 3</a>
                  </li>
              </ul>
          </li>
          <li>
              <a href="#">
                  <i class="fas fa-image"></i>
                  Portfolio
              </a>
          </li>
          <li>
              <a href="#">
                  <i class="fas fa-question"></i>
                  FAQ
              </a>
          </li>
          <li>
              <a href="#">
                  <i class="fas fa-paper-plane"></i>
                  Contact
              </a>
          </li>
      </ul>
  </nav>

app/views/layouts/users_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title)  %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/users/header' %>
    <div class="wrapper">
      <%= render 'layouts/users/side_nav' %>
      <div id="content">
        <%= yield %>
      </div>
    </div>
    <div id="modal-container"></div>
  </body>
</html>

app/views/user_controllers/home_pages/index.html.erb
<div class="custom-container">

    <div class="product-wrapper">
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
        <div class="custom-card">
            <%= link_to user_controllers_show_path do %>
                <div class="img">
                    <%= image_tag "demo1.jpg", class: "product-img" %>
                </div>
                <div class="name-price">
                    <h3>Váy xẻ cổ cong</h3>
                    <h4>348.000đ</h4>
                </div>
                <% end %>
        </div>
    </div>
</div>

app/views/user_controllers/home_pages/show.html.erb
<div class="infor-wrapper">
  <div class="detail-wrapper">
    <div class="img">
      <%= image_tag "demo_600x799.webp", class: "product-img" %>

    </div>
    <div class="order">
      <h3>SHEIN Váy Xẻ Cổ Cong</h3>
      <h2 class="price">348.000đ</h2>
      <%= label_tag 'product', 'Loại' %>
      <%= select_tag 'product', options_for_select(["Đen", "Trắng"] ), multiple: false, label: "Loại", class: '' %>
      <br/>
      <%= label_tag 'count', 'Số lượng' %>
      <%= number_field_tag 'count' %>
      <div class="buy-cart">
        <%= button_tag 'Thêm vào giỏ', type:'button', class:'btn btn-primary' %>
        <%= button_tag 'Mua ngay', type:'button', class:'btn buy-btn' %>
      </div>

      <div class="detail">
        <h3>Chi tiết sản phẩm</h3>
        <div class="brand">
          <%= label_tag 'brand', 'Thương hiệu' %>
          <p  name='brand'>No brand</p>
        </div>
        <div class="pattern">
          <%= label_tag 'pattern', 'Họa tiết' %>
          <p name='pattern'>Patchwork</p>
        </div>
        <div class="origin">
          <%= label_tag 'origin', 'Xuất xứ' %>
          <p name='origin'>Việt Nam</p>
        </div>
      </div>

    </div>
  </div>
  <div class="description">
    <h3>Mô tả sản phẩm</h3>
    <p>    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
    tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
    vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
    no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
  </div>

</div>

app/views/user_controllers/modals/_login_modal.html.erb
<div class="modal" id="loginModal">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <!-- Modal Header -->
          <div class="modal-header">
              <h4 class="modal-title">Đăng nhập</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>

          <!-- Modal body -->
          <div class="modal-body">
              <%= form_for :session, 
                url: user_controllers_authentications_sessions_path, 
                remote: true do |f| %>
                <div class="text-center text-danger" 
                  id="sessions-invalid-email-and-password-error">
                </div>
                <div class="form-group">
                  <%= f.label :email %> 
                  <%= f.email_field :email, class: "form-control" %> 
                </div> 

                <div class="form-group">
                  <%= f.label :password %> 
                  <%= f.password_field :password, class: "form-control" %>
                </div>
                
                <div class="form-check d-inline-block mb-2">
                  <%= f.check_box :remember_me, class: "form-check-input" %>
                  <%= f.label :remember_me, class: "form-check-label" %>
                </div>

                <div class="text-center">
                  <%= f.submit "Sign in", class: "btn mb-3", id: "submitModalLogin" %> 
                  <%= content_tag :span, "Chưa có tài khoản" %>
                  <%= link_to "Đăng kí ngay", 
                    new_user_controllers_authentications_registrations_path, 
                    remote: true %>
                </div>
              <% end %>
          </div>

          <!-- Modal footer -->
          <div class="modal-footer text-center">
              <div class="m-auto">
                  <span>Hoặc đăng nhập với</span>
                  <div class="social-login-logo mt-2">
                      <button class="btn btn-outline-primary login-social-btn text-center">
                  <i class="fab fa-facebook-f d-inline-block"></i>
                </button>
                      <button class="btn btn-outline-danger login-social-btn text-center">
                  <i class="fab fa-google d-inline-block"></i>
                </button>
                      <button class="btn btn-outline-success login-social-btn text-center">
                  <i class="fab fa-instagram d-inline-block"></i>
                </button>

                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

app/views/user_controllers/modals/_registration_modal.html.erb
<div class="modal" id="registrationModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Đăng kí</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
              <%= form_for @registration_form, 
                url: user_controllers_authentications_registrations_path, 
                remote: true do |f| %>
                    <div class="form-group">
                      <%= f.label :name %> 
                      <%= f.text_field :name, class: "form-control" %>
                      <div class="text-danger text-sm font-italic" 
                        id="registrations-name-error">
                      </div>
                    </div>

                    <div class="form-group">
                      <%= f.label :email %> 
                      <%= f.email_field :email, class: "form-control" %>
                      <div class="text-danger text-sm font-italic" 
                        id="registrations-email-error">
                      </div>
                    </div>

                    <div class="form-group">
                      <%= f.label :password %>
                      <%= f.password_field :password, class: "form-control" %>
                    </div>
                      <div class="text-danger text-sm font-italic" 
                        id="registrations-password-error">
                      </div>

                    <div class="form-group">
                      <%= f.label :password_confirmation %> 
                      <%= f.password_field :password_confirmation, class: "form-control" %>
                      <div class="text-danger text-sm font-italic" 
                        id="registrations-password-confirmation-error">
                      </div>
                    </div>

                    <div class="text-center">
                      <%= f.submit "Đăng kí",
                        class: "btn mb-3", id: "submitModalRegistration" %>
                    </div>
                <% end %>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer text-center">
                <div class="m-auto">
                    <span>Hoặc đăng nhập với</span>
                    <div class="social-login-logo mt-2">
                        <button class="btn btn-outline-primary login-social-btn text-center">
                          <i class="fab fa-facebook-f d-inline-block"></i>
                        </button>
                        <button class="btn btn-outline-danger login-social-btn text-center">
                          <i class="fab fa-google d-inline-block"></i>
                        </button>
                        <button class="btn btn-outline-success login-social-btn text-center">
                          <i class="fab fa-instagram d-inline-block"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>